apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-api
  namespace: argocd
  labels:
    app.kubernetes.io/name: demo-api
spec:
  project: default
  source:
    repoURL: https://github.com/kowuoscar/gitops-repo
    targetRevision: HEAD
    path: manifests/demo-api
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true